ARG base_img

FROM $base_img

USER root

COPY requirements_wo_pyspark.txt /
RUN pip install -r /requirements_wo_pyspark.txt

ENV PATH=$PATH:/app
ENV PYTHONPATH /app

COPY *.jar /opt/spark/jars/
COPY aks_executor.py /app/
ADD tasks /app/tasks